/* annoce */
export const GETALLANNONCE ="GETALLANNONCE" ;
export const GETONEANNONCE = "GETONEANNONCE";
export const  GETALLANNONCEE ="GETALLANNONCEE"
export const UPDATEANNAONCE = "UPDATEANNAONCE" ;
export const DELATEANNOCE = "DELATEANNOCE"  ;
export const POSTANNONCE = "POSTANNONCE"   ;
export const SORTSTATE = "SORTSTATE"
/*FAVORITE */
export const GETALLFAVORITE="GETALLFAVORITE"


/*personne */
export const  GETALLPERSONNE = "GETALLPERSONNE"   ;
export const GETONEUSER = "GETONEUSER"            ;
export const  DELATEPERSONNE="DELATEPERSONNE"    ;
export const  LOGINPERSONNE ="LOGINPERSONNE"     ;
export const SIGNUPPERSONNE = "SIGNUPPERSONNE"    ;
export const DECODETOKEN = "DECODETOKEN"

/* RECUPERER MAIL */
export const RECUPEREMAL="RECUPEREMAL"


/* recuperer tout les message */
export const GETTALLMESSAGE = "GETTALLMESSAGE"
export const DELATEMESSAGE = "DELATEMESSAGE"